name: Close a preview taxonomy in the ICC

on:
  pull_request:
    types: [closed]

env:
  ICC_URL: https://c629-104-28-211-161.ngrok-free.app

jobs:
  close-preview:
    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install the tug
        run: |
          curl -o tug https://downloads.platformatichq.com/tug-linux-main
          chmod +x tug

      - name: Merge a preview taxonomy in the ICC
        if: github.event.pull_request.merged == true
        run: ./tug close --merge --ci=github --reject-unauthorized=false --icc-url=$ICC_URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close a preview taxonomy in the ICC
        if: github.event.pull_request.merged == false
        run: ./tug close --ci=github --reject-unauthorized=false --icc-url=$ICC_URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}